.\" Manpage for camunda-tool
.\" Contact lud.sund@gmail.com to correct errors or typos.

.TH camunda-tool 1 "19 July 2019" "1.0" "camunda-tool manual"

.SH NAME

camunda-tool \- useful wrapper around the Camunda REST API

.SH SYNOPSIS

.B camunda-tool COMMANDS OPTIONS

.SH DESCRIPTION

.B camunda-tool
is a wrapper around the Camunda REST API for interacting with
Camunda BPM from the command line. Designed to give easy and fast access to the
core functionality you need to develop and monitor camunda processes.

.SH COMMANDS

Commands are tokens that does not start with a dash.
.B camunda-tool
expects all commands before any options are given

Valid commands are:

.IP "list <definition>"
lists all currently running process instances of the given definition

.IP "hlist <definition>"
lists all process instances of the given definition

.IP "vars <process-id>"
list the variables of the given process ID.

.IP "start definition variables"
starts an instance of the latest process definition with the given definition key
given start variables.

.IP "monitor <process-id>"

.IP "input-vars <definition>"

.SH OPTIONS

Options begin with one or two dashes.

Valid options are:

.IP "-r, --raw"
Return the raw JSON from the Camunda rest API

.SH EXAMPLES

.IP "List all active process instances"

\fB$\fR camunda-tool list

.IP "Since the program always return JSON, it is easily adaptable to \fBjq\fR"

\fB$\fR camunda-tool list | jq '.[].id'

\fB$\fR camunda-tool list | jq 'map(select(.processDefinitionName == "Invoice Receipt"))'

.SH BUGS

No known bugs.

.SH SEE ALSO

jq(1)

.SH AUTHOR

Ludvig Sundström (lud.sund@gmail.com)
